[package]
name = "day03"
version = "0.1.0"
authors = ["brian-cook <brian.cook@gremlin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
